/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the source repository.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TerrestrialBrainPlugin,
  simpleHash: () => simpleHash,
  stripFrontmatter: () => stripFrontmatter
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  tbEndpointUrl: "",
  excludeTag: "terrestrialBrainExclude",
  debounceMs: 3e5,
  pollIntervalMs: 6e5,
  // 10 minutes
  projectsFolderBase: "projects"
};
var TerrestrialBrainPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    // Persisted hash cache — survives Obsidian restarts, prevents duplicate syncs
    this.syncedHashes = {};
    // Per-file debounce timers — we manage these manually for the long 5-min delay
    this.debounceTimers = /* @__PURE__ */ new Map();
    // Guard to prevent overlapping poll cycles while a confirmation dialog is open
    this.pollInProgress = false;
  }
  async onload() {
    await this.loadSettings();
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file.extension !== "md")
          return;
        this.scheduleSync(file);
      })
    );
    this.addCommand({
      id: "sync-to-terrestrial-brain",
      name: "Sync current note to Terrestrial Brain",
      callback: async () => {
        const file = this.app.workspace.getActiveFile();
        if (!file) {
          new import_obsidian.Notice("No active file");
          return;
        }
        this.cancelTimer(file.path);
        await this.processNote(file, { force: true });
      }
    });
    this.addCommand({
      id: "sync-vault-to-terrestrial-brain",
      name: "Sync entire vault to Terrestrial Brain",
      callback: async () => {
        const files = this.app.vault.getMarkdownFiles();
        const eligible = files.filter((f) => !this.isExcluded(f));
        if (eligible.length === 0) {
          new import_obsidian.Notice("No notes to sync (all excluded or vault empty)");
          return;
        }
        const notice = new import_obsidian.Notice(`\u{1F9E0} Syncing ${eligible.length} notes...`, 0);
        let done = 0;
        let failed = 0;
        for (const file of eligible) {
          this.cancelTimer(file.path);
          try {
            await this.processNote(file, { force: true, silent: true });
            done++;
          } catch (e) {
            failed++;
          }
          notice.setMessage(`\u{1F9E0} Syncing vault... ${done + failed}/${eligible.length}`);
        }
        notice.hide();
        new import_obsidian.Notice(
          failed === 0 ? `\u2705 Vault sync complete \u2014 ${done} notes sent` : `\u26A0\uFE0F Vault sync: ${done} ok, ${failed} failed`
        );
      }
    });
    this.addRibbonIcon("brain", "Sync to Terrestrial Brain", async () => {
      const file = this.app.workspace.getActiveFile();
      if (!file) {
        new import_obsidian.Notice("No active file");
        return;
      }
      this.cancelTimer(file.path);
      await this.processNote(file, { force: true });
    });
    this.addCommand({
      id: "poll-ai-output",
      name: "Pull AI output from Terrestrial Brain",
      callback: async () => {
        await this.pollAIOutput();
      }
    });
    this.addSettingTab(new TBSettingTab(this.app, this));
    window.setTimeout(() => this.pollAIOutput(), 2e3);
    this.registerInterval(
      window.setInterval(() => this.pollAIOutput(), this.settings.pollIntervalMs)
    );
    console.log("Terrestrial Brain Sync loaded");
  }
  onunload() {
    for (const timer of this.debounceTimers.values()) {
      clearTimeout(timer);
    }
    this.debounceTimers.clear();
  }
  // ─── Per-file debounce timer ───────────────────────────────────────────────
  // Each file gets its own timer. Editing the file resets its timer.
  // Only fires after debounceMs of inactivity on that specific file.
  scheduleSync(file) {
    this.cancelTimer(file.path);
    const timer = setTimeout(async () => {
      this.debounceTimers.delete(file.path);
      await this.processNote(file);
    }, this.settings.debounceMs);
    this.debounceTimers.set(file.path, timer);
  }
  cancelTimer(filePath) {
    const existing = this.debounceTimers.get(filePath);
    if (existing) {
      clearTimeout(existing);
      this.debounceTimers.delete(filePath);
    }
  }
  // ─── AI Output Polling ─────────────────────────────────────────────────────
  async pollAIOutput() {
    if (!this.settings.tbEndpointUrl)
      return;
    if (this.pollInProgress)
      return;
    this.pollInProgress = true;
    try {
      const raw = await this.callMCP("get_pending_ai_output", {});
      const outputs = JSON.parse(raw);
      if (!outputs.length)
        return;
      const accepted = await this.showConfirmationDialog(outputs);
      if (accepted) {
        await this.deliverOutputs(outputs);
      } else {
        await this.rejectOutputs(outputs);
      }
    } catch (err) {
      console.error("TB Poll error:", err);
    } finally {
      this.pollInProgress = false;
    }
  }
  showConfirmationDialog(outputs) {
    return new Promise((resolve) => {
      const modal = new AIOutputConfirmModal(this.app, outputs, resolve);
      modal.open();
    });
  }
  async deliverOutputs(outputs) {
    const ids = [];
    for (const output of outputs) {
      const path = output.file_path;
      const folder = path.substring(0, path.lastIndexOf("/"));
      if (folder)
        await this.app.vault.adapter.mkdir(folder);
      await this.app.vault.adapter.write(path, output.content);
      const contentHash = simpleHash(stripFrontmatter(output.content).trim());
      this.syncedHashes[path] = contentHash;
      ids.push(output.id);
    }
    await this.callMCP("mark_ai_output_picked_up", { ids });
    await this.saveSettings();
    new import_obsidian.Notice(`\u{1F9E0} ${outputs.length} AI output${outputs.length > 1 ? "s" : ""} delivered to vault`);
  }
  async rejectOutputs(outputs) {
    const ids = outputs.map((output) => output.id);
    await this.callMCP("reject_ai_output", { ids });
    new import_obsidian.Notice(`\u{1F9E0} ${outputs.length} AI output${outputs.length > 1 ? "s" : ""} rejected`);
  }
  // ─── Core Logic ────────────────────────────────────────────────────────────
  async processNote(file, opts = {}) {
    if (this.isExcluded(file)) {
      if (opts.force && !opts.silent) {
        new import_obsidian.Notice(`\u23ED\uFE0F "${file.basename}" is excluded from Terrestrial Brain`);
      }
      return;
    }
    if (!this.settings.tbEndpointUrl) {
      new import_obsidian.Notice("\u26A0\uFE0F Terrestrial Brain: Set your MCP endpoint URL in settings");
      return;
    }
    const content = await this.app.vault.read(file);
    const stripped = stripFrontmatter(content).trim();
    if (!stripped)
      return;
    const hash = simpleHash(stripped);
    if (!opts.force && this.syncedHashes[file.path] === hash)
      return;
    if (!opts.silent) {
      new import_obsidian.Notice(`\u{1F9E0} Syncing "${file.basename}"...`, 2e3);
    }
    try {
      const result = await this.callMCP("ingest_note", {
        content: stripped,
        title: file.basename,
        note_id: file.path
        // vault-relative path e.g. "Projects/CarChief/sprint-notes.md"
      });
      this.syncedHashes[file.path] = hash;
      await this.saveSettings();
      if (!opts.silent) {
        new import_obsidian.Notice(`\u2705 ${result}`);
      }
    } catch (err) {
      console.error("TB Plugin error:", err);
      if (!opts.silent) {
        new import_obsidian.Notice(`\u274C Terrestrial Brain: ${err.message}`);
      }
    }
  }
  // ─── Exclusion Check ───────────────────────────────────────────────────────
  isExcluded(file) {
    var _a, _b, _c;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache)
      return false;
    const excludeTag = this.settings.excludeTag.replace(/^#/, "");
    if (((_a = cache.frontmatter) == null ? void 0 : _a[excludeTag]) === true)
      return true;
    const excludeTagLower = excludeTag.toLowerCase();
    const inlineTags = ((_b = cache.tags) == null ? void 0 : _b.map((t) => t.tag.replace(/^#/, "").toLowerCase())) || [];
    const fmTags = ((_c = cache.frontmatter) == null ? void 0 : _c.tags) || [];
    const fmTagList = (Array.isArray(fmTags) ? fmTags : [fmTags]).map(
      (t) => String(t).toLowerCase()
    );
    return [...inlineTags, ...fmTagList].includes(excludeTagLower);
  }
  // ─── MCP Call ──────────────────────────────────────────────────────────────
  async callMCP(toolName, args) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k;
    const response = await fetch(this.settings.tbEndpointUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json, text/event-stream"
      },
      body: JSON.stringify({
        jsonrpc: "2.0",
        id: Date.now(),
        method: "tools/call",
        params: { name: toolName, arguments: args }
      })
    });
    if (!response.ok) {
      const body = await response.text();
      throw new Error(`MCP ${response.status}: ${body}`);
    }
    const contentType = response.headers.get("content-type") || "";
    if (contentType.includes("text/event-stream")) {
      const text = await response.text();
      const dataLines = text.split("\n").filter((l) => l.startsWith("data:")).map((l) => l.slice(5).trim()).filter((l) => l && l !== "[DONE]");
      for (const line of dataLines) {
        try {
          const parsed = JSON.parse(line);
          if (parsed.error)
            throw new Error(JSON.stringify(parsed.error));
          const toolResult = parsed.result;
          if (toolResult == null ? void 0 : toolResult.isError) {
            throw new Error(((_b = (_a = toolResult == null ? void 0 : toolResult.content) == null ? void 0 : _a[0]) == null ? void 0 : _b.text) || "Unknown error");
          }
          return ((_d = (_c = toolResult == null ? void 0 : toolResult.content) == null ? void 0 : _c[0]) == null ? void 0 : _d.text) || "Done";
        } catch (e) {
          if (e instanceof SyntaxError)
            continue;
          throw e;
        }
      }
      return "Done";
    } else {
      const result = await response.json();
      if (result.error)
        throw new Error(JSON.stringify(result.error));
      if ((_e = result.result) == null ? void 0 : _e.isError) {
        throw new Error(((_h = (_g = (_f = result.result) == null ? void 0 : _f.content) == null ? void 0 : _g[0]) == null ? void 0 : _h.text) || "Unknown error");
      }
      return ((_k = (_j = (_i = result.result) == null ? void 0 : _i.content) == null ? void 0 : _j[0]) == null ? void 0 : _k.text) || "Done";
    }
  }
  // ─── Settings Persistence ──────────────────────────────────────────────────
  async loadSettings() {
    var _a, _b;
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, (_a = data == null ? void 0 : data.settings) != null ? _a : data);
    this.syncedHashes = (_b = data == null ? void 0 : data.syncedHashes) != null ? _b : {};
  }
  async saveSettings() {
    await this.saveData({
      settings: this.settings,
      syncedHashes: this.syncedHashes
    });
  }
};
var AIOutputConfirmModal = class extends import_obsidian.Modal {
  constructor(app, outputs, onDecision) {
    super(app);
    this.resolved = false;
    this.outputs = outputs;
    this.onDecision = onDecision;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", {
      text: `${this.outputs.length} pending AI output${this.outputs.length > 1 ? "s" : ""}`
    });
    const listContainer = contentEl.createDiv({ cls: "tb-ai-output-list" });
    listContainer.style.maxHeight = "300px";
    listContainer.style.overflowY = "auto";
    listContainer.style.marginBottom = "16px";
    for (const output of this.outputs) {
      const charCount = output.content.length.toLocaleString();
      const item = listContainer.createDiv({ cls: "tb-ai-output-item" });
      item.style.padding = "6px 0";
      item.style.borderBottom = "1px solid var(--background-modifier-border)";
      item.createEl("div", {
        text: output.file_path,
        cls: "tb-ai-output-path"
      }).style.fontWeight = "600";
      item.createEl("div", {
        text: `${charCount} chars`,
        cls: "tb-ai-output-size"
      }).style.color = "var(--text-muted)";
    }
    const buttonContainer = contentEl.createDiv({ cls: "tb-ai-output-buttons" });
    buttonContainer.style.display = "flex";
    buttonContainer.style.justifyContent = "flex-end";
    buttonContainer.style.gap = "8px";
    buttonContainer.style.marginTop = "16px";
    const rejectButton = buttonContainer.createEl("button", { text: "Reject All" });
    rejectButton.addEventListener("click", () => {
      this.resolve(false);
    });
    const acceptButton = buttonContainer.createEl("button", {
      text: "Accept All",
      cls: "mod-cta"
    });
    acceptButton.addEventListener("click", () => {
      this.resolve(true);
    });
  }
  onClose() {
    if (!this.resolved) {
      this.onDecision(false);
    }
    this.contentEl.empty();
  }
  resolve(accepted) {
    this.resolved = true;
    this.onDecision(accepted);
    this.close();
  }
};
var TBSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Terrestrial Brain Sync" });
    containerEl.createEl("p", {
      text: "Syncs all notes in this vault to Terrestrial Brain. Waits until you stop editing before syncing. Notes tagged with the exclude tag are always skipped.",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("Terrestrial Brain MCP Endpoint URL").setDesc("Full URL including the ?key= parameter from your Supabase edge function.").addText(
      (text) => text.setPlaceholder("https://xxx.supabase.co/functions/v1/terrestrial-brain-mcp?key=...").setValue(this.plugin.settings.tbEndpointUrl).onChange(async (value) => {
        this.plugin.settings.tbEndpointUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Exclude tag").setDesc("Notes with this tag are never synced. Default: terrestrialBrainExclude").addText(
      (text) => text.setPlaceholder("terrestrialBrainExclude").setValue(this.plugin.settings.excludeTag).onChange(async (value) => {
        this.plugin.settings.excludeTag = value.trim().replace(/^#/, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync delay (ms)").setDesc(
      "How long to wait after you stop editing before syncing. Default 300000 (5 minutes). Minimum 60000 (1 minute)."
    ).addText(
      (text) => text.setPlaceholder("300000").setValue(String(this.plugin.settings.debounceMs)).onChange(async (value) => {
        const parsed = parseInt(value);
        if (!isNaN(parsed) && parsed >= 6e4) {
          this.plugin.settings.debounceMs = parsed;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("AI output poll interval (ms)").setDesc(
      "How often to check for new AI-generated output. Default 600000 (10 minutes). Minimum 60000 (1 minute)."
    ).addText(
      (text) => text.setPlaceholder("600000").setValue(String(this.plugin.settings.pollIntervalMs)).onChange(async (value) => {
        const parsed = parseInt(value);
        if (!isNaN(parsed) && parsed >= 6e4) {
          this.plugin.settings.pollIntervalMs = parsed;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Projects folder base").setDesc("Base folder for project files in the vault. Default: projects").addText(
      (text) => text.setPlaceholder("projects").setValue(this.plugin.settings.projectsFolderBase).onChange(async (value) => {
        this.plugin.settings.projectsFolderBase = value.trim() || "projects";
        await this.plugin.saveSettings();
      })
    );
  }
};
function stripFrontmatter(content) {
  return content.replace(/^---[\s\S]*?---\n?/, "");
}
function simpleHash(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const chr = str.charCodeAt(i);
    hash = (hash << 5) - hash + chr;
    hash |= 0;
  }
  return String(hash);
}
